name: pratishtha
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+7

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  async: ^2.11.0
  auto_size_text: ^3.0.0
  bubble_tab_indicator: ^0.1.6
  buttons_tabbar: ^1.3.15
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^4.14.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  data_connection_checker_nulls: ^0.0.2
  date_time_picker: ^2.1.0
  excel: ^4.0.2
  figma_squircle: ^0.5.3
  firebase_auth: ^4.16.0
  firebase_auth_platform_interface: ^7.0.9
  firebase_core: ^2.15.0
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_page_transition_plus: ^1.0.2
  flutter_riverpod: ^2.6.1
  flutter_slimy_card: ^1.0.2
  flutter_svg: ^2.0.16
  fluttermoji: ^1.0.2
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.8.0
  gif: ^2.3.0
  glassmorphism: ^3.0.0
  
  google_fonts: ^6.2.1
  image_picker: ^1.0.7
  intl: ^0.17.0
  liquid_progress_indicator_v2: ^0.5.0
  # flutter_page_transition: ^0.1.0
  #liquid_progress_indicator:
  # data_connection_checker: ^0.3.4
  #firebase_messaging: ^11.2.4
  #flutter_local_notifications: ^9.1.5
  uuid: ^4.3.3
  liquid_swipe: ^3.1.0
  loading_indicator: ^3.1.1
  url_launcher: ^6.2.3



  path_provider: ^2.1.2
  youtube_player_flutter: ^8.1.2


  multi_dropdown: ^2.1.3
  page_transition: ^2.1.0
  syncfusion_flutter_calendar: ^21.2.3
  table_calendar: ^3.0.8


  dotted_border: ^2.1.0
  toastification: ^2.3.0
  lottie: ^3.2.0
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_launcher_icons: ^0.9.2
#flutter_icons:
#  android: true
#  ios: true
#  image_path: "assets/images/PratishthaLogo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/InterCollegeSports/
    - assets/gifs/
    - assets/lottie/
    - assets/lottie/tick.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
